sonar.projectKey=singhn15_aircraftmon
sonar.organization=singhn15

sonar.sources=backend,frontend/src
sonar.tests=backend/tests

sonar.python.version=3.14
sonar.python.coverage.reportPaths=backend/coverage.xml

sonar.exclusions=backend/tests/**,**/node_modules/**,**/dist/**
